modLoader="${mod_loader}"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}" 
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description="${mod_description}"

[[dependencies.dragonradarmod]]
modId="citadel"
mandatory=false
versionRange="[1.20.1-2.5.4,)"
ordering="AFTER"
side="BOTH"

[[dependencies.dragonradarmod]]
modId="iceandfire"
mandatory=true
versionRange="[1.20.1-2.1.13,)"
ordering="AFTER"
side="BOTH"
